import "@/styles/globals.css";
import Head from "next/head";
import EmailIcon from "@mui/icons-material/Email";
import { CssBaseline, Box, IconButton } from "@mui/material";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Box sx={{ display: "flex", height: "100vh" }}>
        <Box sx={{ width: 80, background: "#eee", p: 2 }}>
          <IconButton href="/">
            <EmailIcon fontSize="large" />
          </IconButton>
        </Box>
        <Box sx={{ flexGrow: 1 }}>
          <Component {...pageProps} />
        </Box>
      </Box>
    </>
  );
}
